apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: mysql-secret
  
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_USER: cm9vdA==
  #DATABASE_URL: bXlzcWw6Ly9yb290OnBhc3N3b3JkQG15c3FsOjMzMDYva2FuYm9hcmQ=
  #!mysql://user:password@service:port/db