apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase-ingress
spec:
  rules:
  - host: amontana-metabase.my.kube.um.edu.ar
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: metabase-service
            port:
              name: http
