apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:latest
        envFrom:
          - secretRef:
              name: metabase-secrets
        ports:
          - name: metabase
            containerPort: 3000
        volumeMounts:
        - name: metabase-secrets
          mountPath: /metabase-secrets
      volumes:
      - name: metabase-secrets
        secret:
          secretName: metabase-secrets