apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  labels:
    run: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      run: metabase
  template:
    metadata:
      generateName: metabase
      labels:
        run: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: metabase-secrets
        ports:
          - name: metabase
            containerPort: 3000
        volumeMounts:
        - name: metabase-secrets
          mountPath: /metabase-secrets
      volumes:
      - name: metabase-secrets
        secret:
          secretName: metabase-secrets