apiVersion: v1
kind: Secret
metadata:
  name: metabase-secrets
type: Opaque
data:
  MB_DB_TYPE: "bXlzcWw="
  MB_DB_DBNAME: "bWV0YWJhc2UtZGI="
  MB_DB_PORT: "MzMwNg=="
  MB_DB_USER: "cm9vdA=="
  MB_DB_HOST: "bXlzcWwtc2VydmljZQ=="
  MB_DB_PASS: bXlzcWwxMjM0