apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metabase-db
  labels:
    run: metabase-db
spec:
  replicas: 1
  selector:
    matchLabels:
      run: metabase-db
  serviceName: "mysql-service"
  template:
    metadata:
      generateName: metabase-db
      labels:
        run: metabase-db
    spec:
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:1.25.0"
        imagePullPolicy: "IfNotPresent"
        command:  ["rm", "-fr", "/var/lib/mysql/lost+found"]
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: meta-db-secrets
              key: MYSQL_DATABASE
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: meta-db-secrets
              key: MYSQL_ROOT_PASSWORD
        ports:
          - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
      volumes:
      - name: mysql-config
        configMap:
          name: mysql-config
      - name: secret-volume
        secret:
          secretName: meta-db-secrets
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn
      resources:
        requests:
          storage: 10Gi