apiVersion: v1
kind: Secret
metadata:
  name: metabase-secret
data:
  metabase-db-type: bXlzcWw=
  metabase-db-name: bWV0YWJhc2VhcHBkYg==
  metabase-db-port: MzMwNg==
  metabase-db-user: cm9vdA==
  metabase-db-pass: bWV0YXBhc3M=
  metabase-db-host: bWV0YWJhc2UtZGI=
    #metabase-db-uri: bXlzcWw6Ly9tZXRhYmFzZS1kYjozMzA2L21ldGFiYXNlYXBwZGI/dXNlcj1yb290JnBhc3N3b3JkPW1ldGFwYXNzJnVzZVNTTD10cnVl
